-- public.expansions definition

-- Drop table

-- DROP TABLE public.expansions;

CREATE TABLE public.expansions (
                                   id uuid NOT NULL,
                                   external_id varchar(255) NOT NULL,
                                   logo_url varchar(255) NULL,
                                   "name" varchar(255) NOT NULL,
                                   release_date date NOT NULL,
                                   serie_name varchar(255) NOT NULL,
                                   total_cards int4 NOT NULL,
                                   CONSTRAINT expansions_pkey PRIMARY KEY (id),
                                   CONSTRAINT ukfru9e3ksk94ibwqly5mao4ymc UNIQUE (external_id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
                              id uuid NOT NULL,
                              created_at timestamp(6) NULL,
                              email varchar(255) NOT NULL,
                              nickname varchar(255) NOT NULL,
                              "password" varchar(255) NOT NULL,
                              "role" varchar(255) NOT NULL,
                              CONSTRAINT uk2ty1xmrrgtn89xt7kyxx6ta7h UNIQUE (nickname),
                              CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
                              CONSTRAINT users_pkey PRIMARY KEY (id),
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


-- public.cards definition

-- Drop table

-- DROP TABLE public.cards;

CREATE TABLE public.cards (
                              id uuid NOT NULL,
                              card_category varchar(255) NOT NULL,
                              external_id varchar(255) NOT NULL,
                              image_url varchar(255) NULL,
                              "name" varchar(255) NOT NULL,
                              rarity varchar(255) NOT NULL,
                              regulation_mark varchar(255) NULL,
                              expansion_id uuid NOT NULL,
                              CONSTRAINT cards_card_category_check CHECK (((card_category)::text = ANY ((ARRAY['POKEMON'::character varying, 'TRAINER'::character varying, 'ENERGY'::character varying])::text[]))),
    CONSTRAINT cards_pkey PRIMARY KEY (id),
    CONSTRAINT ukbgcdptrqukgyg5g0hxikdnpe6 UNIQUE (external_id),
    CONSTRAINT fktmpfvfl7wojb0pho0gyvexiy8 FOREIGN KEY (expansion_id) REFERENCES public.expansions(id)
);


-- public.decks definition

-- Drop table

-- DROP TABLE public.decks;

CREATE TABLE public.decks (
                              id uuid NOT NULL,
                              is_legal bool NOT NULL,
                              "name" varchar(255) NOT NULL,
                              owner_id uuid NOT NULL,
                              CONSTRAINT decks_pkey PRIMARY KEY (id),
                              CONSTRAINT fk8k4ffc09tylfxg1krjxtdi1ov FOREIGN KEY (owner_id) REFERENCES public.users(id)
);


-- public.inventory_cards definition

-- Drop table

-- DROP TABLE public.inventory_cards;

CREATE TABLE public.inventory_cards (
                                        id uuid NOT NULL,
                                        card_condition varchar(255) NOT NULL,
                                        card_finish varchar(255) NOT NULL,
                                        quantity int4 NOT NULL,
                                        card_id uuid NOT NULL,
                                        owner_id uuid NOT NULL,
                                        CONSTRAINT inventory_cards_card_condition_check CHECK (((card_condition)::text = ANY ((ARRAY['MINT'::character varying, 'NEAR_MINT'::character varying, 'EXCELLENT'::character varying, 'GOOD'::character varying, 'LIGHT_PLAYED'::character varying, 'PLAYED'::character varying, 'POOR'::character varying])::text[]))),
    CONSTRAINT inventory_cards_card_finish_check CHECK (((card_finish)::text = ANY ((ARRAY['NORMAL'::character varying, 'REVERSE_HOLO'::character varying, 'HOLO'::character varying])::text[]))),
    CONSTRAINT inventory_cards_pkey PRIMARY KEY (id),
    CONSTRAINT uk_inventory_user_card_condition_finish UNIQUE (owner_id, card_id, card_condition, card_finish),
    CONSTRAINT fk6r7lomuuufbe04bxptnh0dfu8 FOREIGN KEY (owner_id) REFERENCES public.users(id),
    CONSTRAINT fkgupka0yv57u2k4t3sjcaf894y FOREIGN KEY (card_id) REFERENCES public.cards(id)
);


-- public.refresh_tokens definition

-- Drop table

-- DROP TABLE public.refresh_tokens;

CREATE TABLE public.refresh_tokens (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       expiry_date timestamptz(6) NOT NULL,
                                       "token" varchar(255) NOT NULL,
                                       user_id uuid NULL,
                                       CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
                                       CONSTRAINT uk7tdcd6ab5wsgoudnvj7xf1b7l UNIQUE (user_id),
                                       CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token),
                                       CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.card_types definition

-- Drop table

-- DROP TABLE public.card_types;

CREATE TABLE public.card_types (
                                   card_id uuid NOT NULL,
                                   type_name varchar(255) NULL,
                                   CONSTRAINT card_types_type_name_check CHECK (((type_name)::text = ANY ((ARRAY['COLORLESS'::character varying, 'DARKNESS'::character varying, 'DRAGON'::character varying, 'FAIRY'::character varying, 'FIGHTING'::character varying, 'FIRE'::character varying, 'GRASS'::character varying, 'LIGHTNING'::character varying, 'METAL'::character varying, 'PSYCHIC'::character varying, 'WATER'::character varying])::text[]))),
    CONSTRAINT fkosrqd0tddqcwt1oqp2oy7l0rx FOREIGN KEY (card_id) REFERENCES public.cards(id)
);


-- public.deck_cards definition

-- Drop table

-- DROP TABLE public.deck_cards;

CREATE TABLE public.deck_cards (
                                   id uuid NOT NULL,
                                   quantity int4 NOT NULL,
                                   card_id uuid NOT NULL,
                                   deck_id uuid NOT NULL,
                                   CONSTRAINT deck_cards_pkey PRIMARY KEY (id),
                                   CONSTRAINT uk_deck_card_line UNIQUE (deck_id, card_id),
                                   CONSTRAINT fk3g7jrlmm3h536e2w9v0vm9ufn FOREIGN KEY (deck_id) REFERENCES public.decks(id),
                                   CONSTRAINT fk3rbh4k5sk5oh41good8sdycqk FOREIGN KEY (card_id) REFERENCES public.cards(id)
);